name = "alarms-do"
account_id = "b6641681fe423910342b9ffa1364c76d"
route = { pattern = "*/*", zone_name = "alarms.do" }
main = "worker.js"
compatibility_date = "2023-09-22"
compatibility_flags = ["durable_object_alarms"]

tail_consumers = [{service = "tail", environment = "production"}]

[durable_objects]
bindings = [{name = "ALARM", class_name = "Alarm"}]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Alarm"]