name = "alarms-do"
account_id = "b6641681fe423910342b9ffa1364c76d"
route = { pattern = "*alarms.do/*", zone_id = "" }
main = "worker.js"
compatibility_date = "2022-09-02"

[durable_objects]
bindings = [{name = "ALARM", class_name = "Alarm"}]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Alarm"]